# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrisisApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CrisisApp

pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'Interactable', :path => '../node_modules/react-native-interactable'

  target 'CrisisApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrisisAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CrisisApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CrisisApp-tvOS

end
