# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrisisApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CrisisApp

pod 'React', :path => '../node_modules/react-native'
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'Interactable', :path => '../node_modules/react-native-interactable'
pod "SwiftMonkeyPaws", '~> 2.1.0'

  target 'CrisisApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

    pod 'lottie-ios', :path => '../node_modules/lottie-ios'

    pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'

    pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  end

  target 'CrisisAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'CrisisApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CrisisApp-tvOS

end
